# Generated by Django 5.1.6 on 2025-03-28 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("family_type", models.CharField(max_length=50)),
                ("father_age", models.IntegerField()),
                ("mother_age", models.IntegerField()),
                ("region", models.CharField(max_length=50)),
                ("depression", models.CharField(max_length=20)),
                ("parent_relation", models.CharField(max_length=20)),
                ("friend_relation", models.CharField(max_length=20)),
                ("state", models.CharField(default="낮음", max_length=50)),
                (
                    "teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.member",
                        to_field="userid",
                    ),
                ),
            ],
        ),
    ]
